### ISSUE TITLE
Updating summary values on applying filters

### ISSUE THREAD

**Issue by RVKarmani** [pjcunningham/Flask-Admin-Dashboard-Summary#3]
I had a query regarding how to get the values of the summary change on applying the column_filters function. For example in your Project View,
column_filters = ['cost'], the values of both the summary rows don't change even on applying the filter. As I understand, the rows change if there is a change in the underlying data only but is it possible in my case?
```
list_template = 'admin/model/summary_list.html'
form_columns = ('name', 'cost')
page_size = 10
column_filters=['cost']
```

**Comment by pjcunningham** [comment]
I've updated the project, [`total_cost`](https://github.com/pjcunningham/Flask-Admin-Dashboard-Summary/blob/master/views.py#L72) method now takes into account any applied search/filters.

Also, I've updated [`page_cost`](https://github.com/pjcunningham/Flask-Admin-Dashboard-Summary/blob/master/views.py#L69) method as the page models are available in the `render` method's `kwargs` (`kwargs['data']`) so there is no reason to do any DB queries here.

Cheers, Paul.

**Comment by RVKarmani** [comment]
IT WORKS!!!!
Cheers mate 👍 
Thank you for helping me out.
